version: "3"
services:
    pdfparser:
      build: .
      volumes:
        - ./src:/usr/src/app
        - ./data:/usr/src/app/data
      entrypoint: sh -c "while true; do echo hello; sleep 20000000000000; done" # easier to develop
